"""empty message

Revision ID: b71cf02692d1
Revises: 75b7543fe24e
Create Date: 2022-01-30 22:52:38.521206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71cf02692d1'
down_revision = '75b7543fe24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('mobile_num', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'mobile_num')
    # ### end Alembic commands ###
